# Generated by Django 5.0.6 on 2024-08-16 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('creator_email', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('source_of_data', models.URLField(default='https://drive.google.com/drive/folders/1SMoIKEbqYTU9ah6ne3xjCq_OO0kYk38F')),
                ('version', models.CharField(default=2)),
                ('file', models.FileField(upload_to='media/webapp/')),
                ('format', models.CharField(blank=True, max_length=255, null=True)),
                ('File_name', models.CharField(blank=True, max_length=255, null=True)),
                ('maintainer_email', models.CharField(default='tayebnihel123@gmail.com', max_length=255)),
                ('Creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrpOfDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('datasets', models.ManyToManyField(to='webapp.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='GrpOfUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('admin_grp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups_user', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('creator_email', models.EmailField(max_length=254)),
                ('maintainer_email', models.CharField(default='tayebnihel123@gmail.com', max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_creator', to=settings.AUTH_USER_MODEL)),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_maintainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ORGDB', to='webapp.organization'),
        ),
        migrations.CreateModel(
            name='Req_Access_Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('deny', 'Deny'), ('non_action', 'No Action')], max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_requests', to=settings.AUTH_USER_MODEL)),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_req', to='webapp.dataset')),
                ('grp_users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grp_users_req', to='webapp.grpofusers')),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintainer_requests', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_req', to='webapp.organization')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
