# Generated by Django 5.0.6 on 2024-07-28 17:39
from django.db import migrations

def add_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='admin')
    Group.objects.get_or_create(name='customer')

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),  # Adjust this dependency to match your latest migration in the auth app
        ('webapp', '0001_initial'),  # Replace with the name of your initial migration
    ]

    operations = [
        migrations.RunPython(add_default_groups),
    ]
